name: 'Destroy on success or failure'

on:
  workflow_run:
    workflows: ["Inspec test execution"]
    branches: [main]
    types: 
      - completed
env:
  INST_NAME: NewServiceAMITesting1177DEL 

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials$env:INST_NAME
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ secrets.REGION }}
                 
      - name: Destroy on SUCCESS
        run: |
          ID=`aws ec2 describe-instances --filters 'Name=instance-state-name,Values=running' 'Name=tag:Name,Values=$INST_NAME' --output text --query 'Reservations[*].Instances[*].InstanceId'`
          echo "Destroying $ID"
          aws ec2 terminate-instances --instance-ids $ID    
        
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.REGION }}
              
      - name: Destroy on FAILURE
        run: |
          ID=`aws ec2 describe-instances --filters 'Name=instance-state-name,Values=running' 'Name=tag:Name,Values=$INST_NAME' --output text --query 'Reservations[*].Instances[*].InstanceId'`
          echo "Destroying $ID"
          aws ec2 terminate-instances --instance-ids $ID
