name: 'EC2 Creation'

on:
  push:
    branches:
      - main

jobs:
  deployEC2:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ secrets.REGION }}

      - name: Creating EC2
        run: |
          aws ec2 run-instances --image-id ami-05a0729a7c3121089 --count 1 --instance-type t2.medium --key-name GlobalLogics --security-group-ids sg-0c8925ad61b8ede76 --subnet-id subnet-0b0d514911d387518 --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=NewServiceAMITesting}]" --user-data file://userdata.txt
